language: python
python:
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
    - "3.13"
    - "pypy3"
install: "pip install -r requirements.txt"
script:
    - python setup.py install
    - cd tests && py.test
